# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_text',
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='text'),
        ),
    ]
