# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170123_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_added',
            field=models.DateField(null=True, verbose_name='date_added'),
        ),
    ]
