# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(null=True, verbose_name='date_added'),
        ),
    ]
