# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170124_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 24, 5, 42, 20, 695942, tzinfo=utc), verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
