# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_sample_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
