# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170123_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 23, 16, 43, 14, 338001, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
