# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('forum', '0007_auto_20170123_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
    ]
