# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_usersolution_submitted_on'),
        ('forum', '0009_answer_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_requests_created', to='practice.Category'),
            preserve_default=False,
        ),
    ]
