# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('status_code', models.IntegerField()),
                ('submitted_on', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='testCase',
        ),
        migrations.DeleteModel(
            name='TestCases',
        ),
        migrations.AddField(
            model_name='usersolution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.Question'),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
