# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='testCase',
        ),
        migrations.AddField(
            model_name='question',
            name='input_file',
            field=models.TextField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='output_file',
            field=models.TextField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestCases',
        ),
    ]
