# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20170127_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='status_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
