# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_userquestion_status_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestion',
            new_name='UserSolution',
        ),
    ]
