# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_auto_20170127_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersolution',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 27, 17, 28, 38, 913168, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
